#!/bin/bash -eu

if /usr/bin/systemctl status northern-hemisphere-prod | /bin/grep --word-regexp --no-messages --silent process; then
    /usr/bin/systemctl stop northern-hemisphere-prod;
fi

VERSION=$1
RPM_PATH=/var/lib/go-agent/pipelines/NorthernHemisphere/target/rpm/northern-hemisphere-prod/RPMS/noarch/northern-hemisphere-dev-$VERSION-1.noarch.rpm

remove_old_rpm() {
    sudo yum -y remove northern-hemisphere-prod.noarch
}

install_new_rpm() {
    sudo yum -y install $RPM_PATH
}

run_service(){
    sudo /usr/bin/systemctl daemon-reload
    sudo /usr/bin/systemctl start northern-hemisphere-prod
}

remove_old_rpm
install_new_rpm
run_service

echo "######################## Done ##########################"